# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  # name: 'Self Hosted'
  vmImage: 'ubuntu-latest'

variables:
- name: name
  value: Kyouko
  readonly: true

stages: 
  - stage: Stage1
    jobs:
      - job: Job_1_1
        displayName: 'Run Job_1_1'
        steps:
          - script: echo Hello Madoka!
            displayName: 'Maodka step'
      - job: Job_1_2
        displayName: 'Run Job_1_2'
        steps:
          - script: echo Hello Sayaka!
            displayName: 'Sayaka step'
            
  # - stage: ValidationStage
  #   dependsOn: [Stage1, Stage2]
  #   jobs:
  #     - job: Job_Validation
  #       displayName: 'Run Job_Validation'
  #       pool: server
  #       steps:
  #         - task: ManualValidation@0
  #           timeoutInMinutes: 2
  #           inputs:
  #             notifyUsers: ''
  #             instructions: 'Yo pls validate'
  #             onTimeout: 'resume'
        

  - stage: Stage2
    dependsOn: []
    jobs:
      - job: Job_2_1
        displayName: 'Run Job_2_1'
        steps:
          - script: echo Hello Mami!
            displayName: 'Mami step' 
  
