# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Self Hosted'
  vmImage: ubuntu-latest

variables:
- name: name
  value: Kyouko

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: ls

- bash: |
    echo Madoka~ $(name)
    echo See https://aka.ms/yaml
    echo Kyouko~ ${{ variables.name }}
  displayName: 'Run a multi-line script'
