trigger: none # Disable CI triggers, but schedule/pipeline trigger still works.
# trigger: # This is a CI trigger. Also got Schdeduled trigger (cron) and Pipeline dependency trigger (resources)
#   batch: true # Squash all commits made while build is in progress
#   branches:
#     include:
#       - master

pool:
  # name: 'Self Hosted' # need to install agent on my own laptop/server
  vmImage: 'ubuntu-latest'

variables:
- name: name
  value: Kyouko
  readonly: true

stages: # A stage is like k8s Service, just a logic boundary. Its jobs runs one after another by default.
  - stage: Stage1 
    jobs: # A job is like k8s Pod. All jobs run in the same place. # Deployment job is special, need to create environemnts in ADO panel first.
      - job: Job_1_1 
        displayName: 'Run Job_1_1'
        steps: # A step is like k8s Container. All steps run in a same Pod.
          - script: echo Hello Madoka!
            displayName: 'Maodka step'
      - job: Job_1_2
        displayName: 'Run Job_1_2'
        steps:
          - script: echo Hello Sayaka!
            displayName: 'Sayaka step'
            
  - stage: Stage2
    dependsOn: [] # Run in parallel, if there are more agents available
    jobs:
      - job: Job_2_1
        displayName: 'Run Job_2_1'
        steps:
          - script: echo Hello Mami!
            displayName: 'Mami step'
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
          - script: which node
            displayName: 'Check installed nodejs version'
  
  - stage: ValidationStage
    dependsOn: [Stage1, Stage2]
    jobs:
      - job: Job_Validation
        displayName: 'Run Job_Validation'
        steps:
          - task: ManualValidation@0
            # target: pycontainer # Can specify 
            # condition: succeededOrFailed() # Other options: always(runs even when canceled), canceled, failed, succeeded(default)
            # retryCountOnTaskFailure: 10
            enabled: false # Disabled for now
            timeoutInMinutes: 1
            inputs: # Inputs may not be available for other tasks.
              notifyUsers: ''
              instructions: 'Yo pls validate'
              onTimeout: 'reject'
        