# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Self Hosted'

variables:
- name: name
  value: Kyouko

steps:
- script: echo Hello, world!
  displayName: 'Print hello world'

- bash: |
    ls
    echo Madoka~ $(name)
    echo See https://aka.ms/yaml
    echo Kyouko~ ${{ variables.name }}
  displayName: 'Run a multi-line script'

- script: npm -v
  displayName: 'Run npm'
