# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Self Hosted'

variables:
- name: name
  value: Kyouko

stages: 
  - stage: Stage1
    jobs:
      - job: Job_1-1
        displayName: 'Run Job_1-1'
        steps:
          - script: echo Hello Madoka!
            displayName: 'Maodka step'
      - job: Job_1-2
        displayName: 'Run Job_1-2'
        steps:
          - script: echo Hello Sayaka!
            displayName: 'Sayaka step'
            
  - stage: ValidationStage
    jobs:
      - job: Job_Validation
        displayName: 'Run Job_Validation'
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 2
            inputs:
              notifyUsers: ''
              instructions: 'Yo pls validate'
              onTimeout: 'resume'
        

  - stage: Stage2
    jobs:
      - job: Job_2-1
        displayName: 'Run Job_2-1'
        steps:
          - script: echo Hello Mami!
            displayName: 'Mami step' 
  
